#!/bin/bash




# -------- DEFINITIONS --------

#exit on error
set -e

#current executable directory
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)

#paths
OUT=$pCXD/out
TMP=$OUT/tmp

#config library
CONFIG_CLONE_URL='https://github.com/iasebsil83/Config'
CONFIG_VERSION='python'






# -------- PREPARE ENVIRONMENT --------

#clean
$CXD/clean

#remove previous generations
rm --recursive --force $OUT/src
if [[ ! -d $TMP ]]; then mkdir --parents $TMP; fi

#get config library
if [[ ! -f $TMP/config.py ]]; then
	cd $TMP
	git clone --branch $CONFIG_VERSION $CONFIG_CLONE_URL --quiet config
	mv config/lib/config.py .
	rm --recursive --force config
fi






# -------- EXECUTION --------

#arch given as 1st param
if [[ -z $1 ]]; then
	echo "build: Missing <arch> as 1st argument." >&2
	exit 1
fi

#args
arch=$1
case $arch in

	#valid arch
	'arm'|'arm64'|'x86'|'x86-64');;

	#invalid arch
	*) echo "build: Invalid <arch> given '$arch'." >&2; exit 1;;
esac

#build
$CXD/genSyscalls $arch
